### ISSUE TITLE
A problem occurs when I try to build the data.frame of 7th-prediction-test.R.

### ISSUE THREAD

**Issue by araf-15** [raqueeb/mltraining#5]
I can not make the data.frame. An error occurs. (file: 7th-prediction-test.R; Line No: 149)
The error is:
---------------------------------------------------------------------------------------------
```
> predict7th <- data.frame(PassengerId = test$PassengerId, Survived = MyPredict)
Error in data.frame(PassengerId = test$PassengerId, Survived = MyPredict) : 
  arguments imply differing number of rows: 418, 891
> write.csv(predict7th, file = "tree2.csv", row.names = FALSE)
Error in is.data.frame(x) : object 'predict7th' not found
```
---------------------------------------------------------------------------------------------
I can not make data frame for both 'randmoForest'(Line No: 134) and 'cforest' (Line No: 149).
Is there any solution to this problem. I need help. :(

**Comment by SajjatUddin** [comment]
Script:

MyPredict <- predict(fit2, test, OOB=TRUE, type = "response")
predict7th <- data.frame(PassengerId = test$PassengerId, Survived = MyPredict)
write.csv(predict7th, file = "tree2.csv", row.names = FALSE)

Error occured with a message

Error in data.frame(PassengerId = test$PassengerId, Survived = Prediction) :
arguments imply differing number of rows: 418, 891

by changing the prediction line
object = fit2 & newdata = test

Solution:

MyPredict <- predict(object = fit2, newdata = test, OOB=TRUE, type = "response")
predict7th <- data.frame(PassengerId = test$PassengerId, Survived = MyPredict)
write.csv(predict7th, file = "tree2.csv", row.names = FALSE)
