### ISSUE TITLE
Error in tarfo

### ISSUE THREAD

**Issue by Mahiury** [raqueeb/mltraining#7]
![image](https://user-images.githubusercontent.com/38978022/85841320-c29e1d00-b7bf-11ea-8b83-7304d104ce22.png)
Hi Sir, 
what should i do about this error i followed your instruction but couldn't proceed because of this error. Then i copied your whole code from github & tried running that but it was same again showed this error. 

It will be a great help if you let me know what should i do now.
Thanks,
Mahidul

**Comment by raqueeb** [comment]
It has to be factor.
