### ISSUE TITLE
Script needed

### ISSUE THREAD

**Issue by Tareq-Annan-Joy-enjoy** [raqueeb/mltraining#8]
হাতে কলমে মেশিন লার্নিং(২য় সংস্করন) এর ৭.৫ এর বার প্লটের কোড গুলো খুজে পাচ্ছি না। লিঙ্কটা শেয়ার করলে ভালো হতো

**Comment by TareqAnnan** [comment]
main="Survived (passenger fate)",col="black")

এই লাইনটিতে কিছু আছে, ১। ১ম ব্রাকেট শেষ হয়েছে, শুরু হয়নি। ২। col এর আগের কমাতে এরর দেখাচ্ছে

**Comment by TareqAnnan** [comment]
Problem solved. No Need help about this matter.

For newbie, Books link doesn't match with new link. 
All the bar plot script is here, file name data-munging. 
For future reference Link is here: https://github.com/raqueeb/mltraining/blob/master/ML-workbook/data-munging.R

**Comment by Tareq-Annan-Joy-enjoy** [comment]
Problem solved. No Need help about this matter.

For newbie, Books link doesn't match with new link. 
All the bar plot script is here, file name data-munging. 
For future reference Link is here: https://github.com/raqueeb/mltraining/blob/master/ML-workbook/data-munging.R
