### ISSUE TITLE
Incorrect Answer Using table instead of summary

### ISSUE THREAD

**Issue by Tareq-Annan-Joy-enjoy** [raqueeb/mltraining#9]
হাতে কলমে মেশিন লার্নিং বইয়ের ১২০ পৃষ্ঠায় >summary(train$Sex) করলে যা ঊত্তর হিসেবে দেওয়া আছে তা summary use করলে আসে না, table ব্যবহার করলে আসে

**Comment by raqueeb** [comment]
আমি পরিবর্তী সংস্করণে ঠিক করে দেবো।
